<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;600;700&display=swap" rel="stylesheet" />
		<link rel="stylesheet" href="css/style.css" />
		<title><?= $title ?></title>
	</head>
	<body>
		<nav>
			<a class="brand" href="#" aria-label="Muse home">
				<img src="logo.svg" alt="Muse logo" />
				<span>Muse</span>
			</a>
			<?php if($auth): ?>
			<div>
				<a href="dashboard">Dashboard</a>
				<a href="songs">Songs</a>
			</div>
			<?php else: ?>
			<div>
				<a class="button" href="sign-in">Sign In</a>
			</div>
			<?php endif; ?>
		</nav>
		<?= $content ?>
	</body>
</html>